#pragma once

#include "DrawableGameComponent.h"
#include "Scene.h"
#include "CargoTrain.h"
#include "PassengerTrain.h"
#include "Track.h"
#include "GreenSoldier.h"
#include "Policeman.h"
#include "Bench.h"
#include "ConcreteWall.h"
#include "StoneGround.h"
#include "GrassGround.h"
#include "PlatformGround1.h"
#include "PlatformGround2.h"
#include "DoubleStreetLampPost.h"
#include "DoubleStreetLampPostWithMegaphone.h"
#include "SingleStreetLampPost.h"